// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// axil
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of buffer_status
//        bit 31~0 - buffer_status[31:0] (Read)
// 0x14 : Control signal of buffer_status
//        bit 0  - buffer_status_ap_vld (Read/COR)
//        others - reserved
// 0x18 : Data signal of buffer_ack
//        bit 31~0 - buffer_ack[31:0] (Read/Write)
// 0x1c : reserved
// 0x38 : Data signal of run
//        bit 0  - run[0] (Read/Write)
//        others - reserved
// 0x3c : reserved
// 0x40 : Data signal of DDROFFSET_V
//        bit 31~0 - DDROFFSET_V[31:0] (Read/Write)
// 0x44 : reserved
// 0x20 ~
// 0x2f : Memory 'buffer_seq' (2 * 64b)
//        Word 2n   : bit [31:0] - buffer_seq[n][31: 0]
//        Word 2n+1 : bit [31:0] - buffer_seq[n][63:32]
// 0x30 ~
// 0x37 : Memory 'bufsize' (2 * 32b)
//        Word n : bit [31:0] - bufsize[n]
// 0x60 ~
// 0x7f : Memory 'stat_counter' (4 * 64b)
//        Word 2n   : bit [31:0] - stat_counter[n][31: 0]
//        Word 2n+1 : bit [31:0] - stat_counter[n][63:32]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDATA_MOVER_AXIL_ADDR_BUFFER_STATUS_DATA 0x10
#define XDATA_MOVER_AXIL_BITS_BUFFER_STATUS_DATA 32
#define XDATA_MOVER_AXIL_ADDR_BUFFER_STATUS_CTRL 0x14
#define XDATA_MOVER_AXIL_ADDR_BUFFER_ACK_DATA    0x18
#define XDATA_MOVER_AXIL_BITS_BUFFER_ACK_DATA    32
#define XDATA_MOVER_AXIL_ADDR_RUN_DATA           0x38
#define XDATA_MOVER_AXIL_BITS_RUN_DATA           1
#define XDATA_MOVER_AXIL_ADDR_DDROFFSET_V_DATA   0x40
#define XDATA_MOVER_AXIL_BITS_DDROFFSET_V_DATA   32
#define XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE    0x20
#define XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_HIGH    0x2f
#define XDATA_MOVER_AXIL_WIDTH_BUFFER_SEQ        64
#define XDATA_MOVER_AXIL_DEPTH_BUFFER_SEQ        2
#define XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE       0x30
#define XDATA_MOVER_AXIL_ADDR_BUFSIZE_HIGH       0x37
#define XDATA_MOVER_AXIL_WIDTH_BUFSIZE           32
#define XDATA_MOVER_AXIL_DEPTH_BUFSIZE           2
#define XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE  0x60
#define XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_HIGH  0x7f
#define XDATA_MOVER_AXIL_WIDTH_STAT_COUNTER      64
#define XDATA_MOVER_AXIL_DEPTH_STAT_COUNTER      4

