# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Owner/Documents/GitHub/R76Firmware/r5560_sdk/NaI_array_spectra/V2/retarget/output/killspectra/killspectra.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_data_mover_0_0/ZynqDesign_data_mover_0_0.xci
# IP: The module: 'ZynqDesign_data_mover_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Owner/Documents/GitHub/R76Firmware/r5560_sdk/NaI_array_spectra/V2/retarget/output/killspectra/killspectra.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_data_mover_0_0/constraints/data_mover_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqDesign_data_mover_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Owner/Documents/GitHub/R76Firmware/r5560_sdk/NaI_array_spectra/V2/retarget/output/killspectra/killspectra.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_data_mover_0_0/ZynqDesign_data_mover_0_0.xci
# IP: The module: 'ZynqDesign_data_mover_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Owner/Documents/GitHub/R76Firmware/r5560_sdk/NaI_array_spectra/V2/retarget/output/killspectra/killspectra.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_data_mover_0_0/constraints/data_mover_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqDesign_data_mover_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
