// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdata_mover.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XData_mover_CfgInitialize(XData_mover *InstancePtr, XData_mover_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axil_BaseAddress = ConfigPtr->Axil_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

u32 XData_mover_Get_buffer_status(XData_mover *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XData_mover_ReadReg(InstancePtr->Axil_BaseAddress, XDATA_MOVER_AXIL_ADDR_BUFFER_STATUS_DATA);
    return Data;
}

u32 XData_mover_Get_buffer_status_vld(XData_mover *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XData_mover_ReadReg(InstancePtr->Axil_BaseAddress, XDATA_MOVER_AXIL_ADDR_BUFFER_STATUS_CTRL);
    return Data & 0x1;
}

void XData_mover_Set_buffer_ack(XData_mover *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XData_mover_WriteReg(InstancePtr->Axil_BaseAddress, XDATA_MOVER_AXIL_ADDR_BUFFER_ACK_DATA, Data);
}

u32 XData_mover_Get_buffer_ack(XData_mover *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XData_mover_ReadReg(InstancePtr->Axil_BaseAddress, XDATA_MOVER_AXIL_ADDR_BUFFER_ACK_DATA);
    return Data;
}

void XData_mover_Set_run(XData_mover *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XData_mover_WriteReg(InstancePtr->Axil_BaseAddress, XDATA_MOVER_AXIL_ADDR_RUN_DATA, Data);
}

u32 XData_mover_Get_run(XData_mover *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XData_mover_ReadReg(InstancePtr->Axil_BaseAddress, XDATA_MOVER_AXIL_ADDR_RUN_DATA);
    return Data;
}

void XData_mover_Set_DDROFFSET_V(XData_mover *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XData_mover_WriteReg(InstancePtr->Axil_BaseAddress, XDATA_MOVER_AXIL_ADDR_DDROFFSET_V_DATA, Data);
}

u32 XData_mover_Get_DDROFFSET_V(XData_mover *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XData_mover_ReadReg(InstancePtr->Axil_BaseAddress, XDATA_MOVER_AXIL_ADDR_DDROFFSET_V_DATA);
    return Data;
}

u32 XData_mover_Get_buffer_seq_BaseAddress(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE);
}

u32 XData_mover_Get_buffer_seq_HighAddress(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_HIGH);
}

u32 XData_mover_Get_buffer_seq_TotalBytes(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_HIGH - XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE + 1);
}

u32 XData_mover_Get_buffer_seq_BitWidth(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDATA_MOVER_AXIL_WIDTH_BUFFER_SEQ;
}

u32 XData_mover_Get_buffer_seq_Depth(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDATA_MOVER_AXIL_DEPTH_BUFFER_SEQ;
}

u32 XData_mover_Write_buffer_seq_Words(XData_mover *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_HIGH - XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XData_mover_Read_buffer_seq_Words(XData_mover *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_HIGH - XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE + (offset + i)*4);
    }
    return length;
}

u32 XData_mover_Write_buffer_seq_Bytes(XData_mover *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_HIGH - XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XData_mover_Read_buffer_seq_Bytes(XData_mover *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_HIGH - XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFFER_SEQ_BASE + offset + i);
    }
    return length;
}

u32 XData_mover_Get_bufsize_BaseAddress(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE);
}

u32 XData_mover_Get_bufsize_HighAddress(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFSIZE_HIGH);
}

u32 XData_mover_Get_bufsize_TotalBytes(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XDATA_MOVER_AXIL_ADDR_BUFSIZE_HIGH - XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE + 1);
}

u32 XData_mover_Get_bufsize_BitWidth(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDATA_MOVER_AXIL_WIDTH_BUFSIZE;
}

u32 XData_mover_Get_bufsize_Depth(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDATA_MOVER_AXIL_DEPTH_BUFSIZE;
}

u32 XData_mover_Write_bufsize_Words(XData_mover *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDATA_MOVER_AXIL_ADDR_BUFSIZE_HIGH - XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XData_mover_Read_bufsize_Words(XData_mover *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDATA_MOVER_AXIL_ADDR_BUFSIZE_HIGH - XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE + (offset + i)*4);
    }
    return length;
}

u32 XData_mover_Write_bufsize_Bytes(XData_mover *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDATA_MOVER_AXIL_ADDR_BUFSIZE_HIGH - XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XData_mover_Read_bufsize_Bytes(XData_mover *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDATA_MOVER_AXIL_ADDR_BUFSIZE_HIGH - XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_BUFSIZE_BASE + offset + i);
    }
    return length;
}

u32 XData_mover_Get_stat_counter_BaseAddress(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE);
}

u32 XData_mover_Get_stat_counter_HighAddress(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_HIGH);
}

u32 XData_mover_Get_stat_counter_TotalBytes(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_HIGH - XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE + 1);
}

u32 XData_mover_Get_stat_counter_BitWidth(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDATA_MOVER_AXIL_WIDTH_STAT_COUNTER;
}

u32 XData_mover_Get_stat_counter_Depth(XData_mover *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDATA_MOVER_AXIL_DEPTH_STAT_COUNTER;
}

u32 XData_mover_Write_stat_counter_Words(XData_mover *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_HIGH - XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XData_mover_Read_stat_counter_Words(XData_mover *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_HIGH - XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE + (offset + i)*4);
    }
    return length;
}

u32 XData_mover_Write_stat_counter_Bytes(XData_mover *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_HIGH - XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XData_mover_Read_stat_counter_Bytes(XData_mover *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_HIGH - XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axil_BaseAddress + XDATA_MOVER_AXIL_ADDR_STAT_COUNTER_BASE + offset + i);
    }
    return length;
}

