lappend pragmaStatus0 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "example" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'example' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "example" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'example' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "example" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'example' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus15 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus16 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus17 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus18 {pragma "INTERFACE" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus19 {pragma "UNROLL" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover/seq_buf" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus20 {pragma "UNROLL" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover/reset_flag_loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus21 {pragma "UNROLL" source "C:/GIT/R5560_FRAMEWORK_45/ip_repo/DMATDCZynq/DmaTDC.cpp" location "data_mover/seq_buf2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
