:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2017.4
:: Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

C:/Xilinx/Vivado/2017.4/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z030fbg676-2 ../NuclearInstruments_hls_data_mover_2_0.zip
