# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/HDL/DT5560_pins.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: ip/main_clock/main_clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_clock || ORIG_REF_NAME==main_clock} -quiet] -quiet

# Block Designs: bd/ZynqDesign/ZynqDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign || ORIG_REF_NAME==ZynqDesign} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_ADCSyncModule_0_0/ZynqDesign_ADCSyncModule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_ADCSyncModule_0_0 || ORIG_REF_NAME==ZynqDesign_ADCSyncModule_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_FIRMWAREBUILD_0/ZynqDesign_FIRMWAREBUILD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_FIRMWAREBUILD_0 || ORIG_REF_NAME==ZynqDesign_FIRMWAREBUILD_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_FIRMWAREOPTIONS_0/ZynqDesign_FIRMWAREOPTIONS_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_FIRMWAREOPTIONS_0 || ORIG_REF_NAME==ZynqDesign_FIRMWAREOPTIONS_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_FIRMWAREVERSION_0/ZynqDesign_FIRMWAREVERSION_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_FIRMWAREVERSION_0 || ORIG_REF_NAME==ZynqDesign_FIRMWAREVERSION_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_FS_0_AXIFIFO_0/ZynqDesign_FS_0_AXIFIFO_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_FS_0_AXIFIFO_0 || ORIG_REF_NAME==ZynqDesign_FS_0_AXIFIFO_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_FirmwareStatus_0_0/ZynqDesign_FirmwareStatus_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_FirmwareStatus_0_0 || ORIG_REF_NAME==ZynqDesign_FirmwareStatus_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_IICBaseInterconnection_0_0/ZynqDesign_IICBaseInterconnection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_IICBaseInterconnection_0_0 || ORIG_REF_NAME==ZynqDesign_IICBaseInterconnection_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_NIDNAPort_0_0/ZynqDesign_NIDNAPort_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_NIDNAPort_0_0 || ORIG_REF_NAME==ZynqDesign_NIDNAPort_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_OPTOLINK_0_0/ZynqDesign_OPTOLINK_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_OPTOLINK_0_0 || ORIG_REF_NAME==ZynqDesign_OPTOLINK_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_OPTOLINK_1_0/ZynqDesign_OPTOLINK_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_OPTOLINK_1_0 || ORIG_REF_NAME==ZynqDesign_OPTOLINK_1_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_RESET_RX_0/ZynqDesign_RESET_RX_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_RESET_RX_0 || ORIG_REF_NAME==ZynqDesign_RESET_RX_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_RESET_TX_0/ZynqDesign_RESET_TX_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_RESET_TX_0 || ORIG_REF_NAME==ZynqDesign_RESET_TX_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_axi_amm_bridge_0_0/ZynqDesign_axi_amm_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_axi_amm_bridge_0_0 || ORIG_REF_NAME==ZynqDesign_axi_amm_bridge_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_axi_iic_0_0/ZynqDesign_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_axi_iic_0_0 || ORIG_REF_NAME==ZynqDesign_axi_iic_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_axi_interconnect_0_0/ZynqDesign_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_axi_interconnect_0_0 || ORIG_REF_NAME==ZynqDesign_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_axis_data_fifo_0_0/ZynqDesign_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_axis_data_fifo_0_0 || ORIG_REF_NAME==ZynqDesign_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_axis_data_fifo_1_0/ZynqDesign_axis_data_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_axis_data_fifo_1_0 || ORIG_REF_NAME==ZynqDesign_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_axis_data_fifo_2_0/ZynqDesign_axis_data_fifo_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_axis_data_fifo_2_0 || ORIG_REF_NAME==ZynqDesign_axis_data_fifo_2_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_axis_data_fifo_3_0/ZynqDesign_axis_data_fifo_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_axis_data_fifo_3_0 || ORIG_REF_NAME==ZynqDesign_axis_data_fifo_3_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_data_mover_0_0/ZynqDesign_data_mover_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_data_mover_0_0 || ORIG_REF_NAME==ZynqDesign_data_mover_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_processing_system7_0_0/ZynqDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_processing_system7_0_0 || ORIG_REF_NAME==ZynqDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_ps7_0_axi_periph_0/ZynqDesign_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZynqDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_rst_ps7_0_125M_0/ZynqDesign_rst_ps7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_rst_ps7_0_125M_0 || ORIG_REF_NAME==ZynqDesign_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_rst_ps7_0_125M1_0/ZynqDesign_rst_ps7_0_125M1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_rst_ps7_0_125M1_0 || ORIG_REF_NAME==ZynqDesign_rst_ps7_0_125M1_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_tft_display_0_0/ZynqDesign_tft_display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_tft_display_0_0 || ORIG_REF_NAME==ZynqDesign_tft_display_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_util_vector_logic_0_0/ZynqDesign_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_util_vector_logic_0_0 || ORIG_REF_NAME==ZynqDesign_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_util_vector_logic_1_0/ZynqDesign_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_util_vector_logic_1_0 || ORIG_REF_NAME==ZynqDesign_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_xbar_0/ZynqDesign_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_xbar_0 || ORIG_REF_NAME==ZynqDesign_xbar_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_auto_cc_1/ZynqDesign_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_auto_cc_1 || ORIG_REF_NAME==ZynqDesign_auto_cc_1} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_auto_cc_0/ZynqDesign_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_auto_cc_0 || ORIG_REF_NAME==ZynqDesign_auto_cc_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_auto_pc_1/ZynqDesign_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_auto_pc_1 || ORIG_REF_NAME==ZynqDesign_auto_pc_1} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_auto_pc_0/ZynqDesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_auto_pc_0 || ORIG_REF_NAME==ZynqDesign_auto_pc_0} -quiet] -quiet

# IP: bd/ZynqDesign/ip/ZynqDesign_auto_us_0/ZynqDesign_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqDesign_auto_us_0 || ORIG_REF_NAME==ZynqDesign_auto_us_0} -quiet] -quiet

# XDC: bd/ZynqDesign/ZynqDesign_ooc.xdc
