// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="data_mover,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z045ffg676-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.000000,HLS_SYN_LAT=1372,HLS_SYN_TPT=none,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=2254,HLS_SYN_LUT=2522}" *)

module data_mover (
        ap_clk,
        ap_rst_n,
        m_axi_a_V_AWVALID,
        m_axi_a_V_AWREADY,
        m_axi_a_V_AWADDR,
        m_axi_a_V_AWID,
        m_axi_a_V_AWLEN,
        m_axi_a_V_AWSIZE,
        m_axi_a_V_AWBURST,
        m_axi_a_V_AWLOCK,
        m_axi_a_V_AWCACHE,
        m_axi_a_V_AWPROT,
        m_axi_a_V_AWQOS,
        m_axi_a_V_AWREGION,
        m_axi_a_V_AWUSER,
        m_axi_a_V_WVALID,
        m_axi_a_V_WREADY,
        m_axi_a_V_WDATA,
        m_axi_a_V_WSTRB,
        m_axi_a_V_WLAST,
        m_axi_a_V_WID,
        m_axi_a_V_WUSER,
        m_axi_a_V_ARVALID,
        m_axi_a_V_ARREADY,
        m_axi_a_V_ARADDR,
        m_axi_a_V_ARID,
        m_axi_a_V_ARLEN,
        m_axi_a_V_ARSIZE,
        m_axi_a_V_ARBURST,
        m_axi_a_V_ARLOCK,
        m_axi_a_V_ARCACHE,
        m_axi_a_V_ARPROT,
        m_axi_a_V_ARQOS,
        m_axi_a_V_ARREGION,
        m_axi_a_V_ARUSER,
        m_axi_a_V_RVALID,
        m_axi_a_V_RREADY,
        m_axi_a_V_RDATA,
        m_axi_a_V_RLAST,
        m_axi_a_V_RID,
        m_axi_a_V_RUSER,
        m_axi_a_V_RRESP,
        m_axi_a_V_BVALID,
        m_axi_a_V_BREADY,
        m_axi_a_V_BRESP,
        m_axi_a_V_BID,
        m_axi_a_V_BUSER,
        stream0_V_V_TDATA,
        stream0_V_V_TVALID,
        stream0_V_V_TREADY,
        debug_buffer_status,
        debug_buffer_status_ap_vld,
        debug_bufsel_0,
        debug_bufsel_0_ap_vld,
        debug_buf0_p,
        debug_buf0_p_ap_vld,
        debug_inbuffer_pointer,
        debug_inbuffer_pointer_ap_vld,
        debug_dst_var_V,
        debug_dst_var_V_ap_vld,
        interrupt_r,
        interrupt_r_ap_vld,
        s_axi_axil_AWVALID,
        s_axi_axil_AWREADY,
        s_axi_axil_AWADDR,
        s_axi_axil_WVALID,
        s_axi_axil_WREADY,
        s_axi_axil_WDATA,
        s_axi_axil_WSTRB,
        s_axi_axil_ARVALID,
        s_axi_axil_ARREADY,
        s_axi_axil_ARADDR,
        s_axi_axil_RVALID,
        s_axi_axil_RREADY,
        s_axi_axil_RDATA,
        s_axi_axil_RRESP,
        s_axi_axil_BVALID,
        s_axi_axil_BREADY,
        s_axi_axil_BRESP
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_pp0_stage0 = 15'd16;
parameter    ap_ST_fsm_state8 = 15'd32;
parameter    ap_ST_fsm_state9 = 15'd64;
parameter    ap_ST_fsm_state10 = 15'd128;
parameter    ap_ST_fsm_state11 = 15'd256;
parameter    ap_ST_fsm_state12 = 15'd512;
parameter    ap_ST_fsm_state13 = 15'd1024;
parameter    ap_ST_fsm_state14 = 15'd2048;
parameter    ap_ST_fsm_state15 = 15'd4096;
parameter    ap_ST_fsm_state16 = 15'd8192;
parameter    ap_ST_fsm_state17 = 15'd16384;
parameter    C_S_AXI_AXIL_DATA_WIDTH = 32;
parameter    C_S_AXI_AXIL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_A_V_ID_WIDTH = 1;
parameter    C_M_AXI_A_V_ADDR_WIDTH = 32;
parameter    C_M_AXI_A_V_DATA_WIDTH = 32;
parameter    C_M_AXI_A_V_AWUSER_WIDTH = 1;
parameter    C_M_AXI_A_V_ARUSER_WIDTH = 1;
parameter    C_M_AXI_A_V_WUSER_WIDTH = 1;
parameter    C_M_AXI_A_V_RUSER_WIDTH = 1;
parameter    C_M_AXI_A_V_BUSER_WIDTH = 1;
parameter    C_M_AXI_A_V_TARGET_ADDR = 0;
parameter    C_M_AXI_A_V_USER_VALUE = 0;
parameter    C_M_AXI_A_V_PROT_VALUE = 0;
parameter    C_M_AXI_A_V_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXIL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_A_V_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_a_V_AWVALID;
input   m_axi_a_V_AWREADY;
output  [C_M_AXI_A_V_ADDR_WIDTH - 1:0] m_axi_a_V_AWADDR;
output  [C_M_AXI_A_V_ID_WIDTH - 1:0] m_axi_a_V_AWID;
output  [7:0] m_axi_a_V_AWLEN;
output  [2:0] m_axi_a_V_AWSIZE;
output  [1:0] m_axi_a_V_AWBURST;
output  [1:0] m_axi_a_V_AWLOCK;
output  [3:0] m_axi_a_V_AWCACHE;
output  [2:0] m_axi_a_V_AWPROT;
output  [3:0] m_axi_a_V_AWQOS;
output  [3:0] m_axi_a_V_AWREGION;
output  [C_M_AXI_A_V_AWUSER_WIDTH - 1:0] m_axi_a_V_AWUSER;
output   m_axi_a_V_WVALID;
input   m_axi_a_V_WREADY;
output  [C_M_AXI_A_V_DATA_WIDTH - 1:0] m_axi_a_V_WDATA;
output  [C_M_AXI_A_V_WSTRB_WIDTH - 1:0] m_axi_a_V_WSTRB;
output   m_axi_a_V_WLAST;
output  [C_M_AXI_A_V_ID_WIDTH - 1:0] m_axi_a_V_WID;
output  [C_M_AXI_A_V_WUSER_WIDTH - 1:0] m_axi_a_V_WUSER;
output   m_axi_a_V_ARVALID;
input   m_axi_a_V_ARREADY;
output  [C_M_AXI_A_V_ADDR_WIDTH - 1:0] m_axi_a_V_ARADDR;
output  [C_M_AXI_A_V_ID_WIDTH - 1:0] m_axi_a_V_ARID;
output  [7:0] m_axi_a_V_ARLEN;
output  [2:0] m_axi_a_V_ARSIZE;
output  [1:0] m_axi_a_V_ARBURST;
output  [1:0] m_axi_a_V_ARLOCK;
output  [3:0] m_axi_a_V_ARCACHE;
output  [2:0] m_axi_a_V_ARPROT;
output  [3:0] m_axi_a_V_ARQOS;
output  [3:0] m_axi_a_V_ARREGION;
output  [C_M_AXI_A_V_ARUSER_WIDTH - 1:0] m_axi_a_V_ARUSER;
input   m_axi_a_V_RVALID;
output   m_axi_a_V_RREADY;
input  [C_M_AXI_A_V_DATA_WIDTH - 1:0] m_axi_a_V_RDATA;
input   m_axi_a_V_RLAST;
input  [C_M_AXI_A_V_ID_WIDTH - 1:0] m_axi_a_V_RID;
input  [C_M_AXI_A_V_RUSER_WIDTH - 1:0] m_axi_a_V_RUSER;
input  [1:0] m_axi_a_V_RRESP;
input   m_axi_a_V_BVALID;
output   m_axi_a_V_BREADY;
input  [1:0] m_axi_a_V_BRESP;
input  [C_M_AXI_A_V_ID_WIDTH - 1:0] m_axi_a_V_BID;
input  [C_M_AXI_A_V_BUSER_WIDTH - 1:0] m_axi_a_V_BUSER;
input  [63:0] stream0_V_V_TDATA;
input   stream0_V_V_TVALID;
output   stream0_V_V_TREADY;
output  [31:0] debug_buffer_status;
output   debug_buffer_status_ap_vld;
output  [31:0] debug_bufsel_0;
output   debug_bufsel_0_ap_vld;
output  [31:0] debug_buf0_p;
output   debug_buf0_p_ap_vld;
output  [31:0] debug_inbuffer_pointer;
output   debug_inbuffer_pointer_ap_vld;
output  [63:0] debug_dst_var_V;
output   debug_dst_var_V_ap_vld;
output   interrupt_r;
output   interrupt_r_ap_vld;
input   s_axi_axil_AWVALID;
output   s_axi_axil_AWREADY;
input  [C_S_AXI_AXIL_ADDR_WIDTH - 1:0] s_axi_axil_AWADDR;
input   s_axi_axil_WVALID;
output   s_axi_axil_WREADY;
input  [C_S_AXI_AXIL_DATA_WIDTH - 1:0] s_axi_axil_WDATA;
input  [C_S_AXI_AXIL_WSTRB_WIDTH - 1:0] s_axi_axil_WSTRB;
input   s_axi_axil_ARVALID;
output   s_axi_axil_ARREADY;
input  [C_S_AXI_AXIL_ADDR_WIDTH - 1:0] s_axi_axil_ARADDR;
output   s_axi_axil_RVALID;
input   s_axi_axil_RREADY;
output  [C_S_AXI_AXIL_DATA_WIDTH - 1:0] s_axi_axil_RDATA;
output  [1:0] s_axi_axil_RRESP;
output   s_axi_axil_BVALID;
input   s_axi_axil_BREADY;
output  [1:0] s_axi_axil_BRESP;

reg stream0_V_V_TREADY;
reg[31:0] debug_buffer_status;
reg debug_buffer_status_ap_vld;
reg debug_bufsel_0_ap_vld;
reg debug_buf0_p_ap_vld;
reg debug_inbuffer_pointer_ap_vld;
reg debug_dst_var_V_ap_vld;
reg interrupt_r;
reg interrupt_r_ap_vld;

reg    ap_rst_n_inv;
reg   [31:0] buffer_status;
reg    buffer_status_ap_vld;
wire   [31:0] buffer_ack;
reg   [0:0] buffer_seq_address0;
reg    buffer_seq_ce0;
reg    buffer_seq_we0;
reg   [63:0] buffer_seq_d0;
reg   [0:0] bufsize_address0;
reg    bufsize_ce0;
reg    bufsize_we0;
reg   [31:0] bufsize_d0;
wire    run;
wire   [31:0] DDROFFSET_V;
reg   [1:0] stat_counter_address0;
reg    stat_counter_ce0;
reg    stat_counter_we0;
reg   [63:0] stat_counter_d0;
reg   [0:0] bufstatus_0;
reg   [0:0] bufstatus_1;
reg   [31:0] inbuffer_pointer;
reg   [63:0] out_counter;
reg   [63:0] lost_counter;
reg   [31:0] buftimeout;
reg   [0:0] bufsel;
reg   [0:0] swap_timeout;
reg   [31:0] buf_p;
reg   [11:0] inbuffer_V_address0;
reg    inbuffer_V_ce0;
reg    inbuffer_V_we0;
wire   [31:0] inbuffer_V_d0;
wire   [31:0] inbuffer_V_q0;
wire   [11:0] inbuffer_V_address1;
reg    inbuffer_V_ce1;
reg    inbuffer_V_we1;
wire   [31:0] inbuffer_V_d1;
reg   [63:0] bsc;
reg   [63:0] bsq_0;
reg   [63:0] bsq_1;
reg   [31:0] obuffer_ack;
reg    a_V_blk_n_AW;
(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state4;
reg    a_V_blk_n_W;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond3_reg_1424;
reg   [0:0] ap_reg_pp0_iter1_exitcond3_reg_1424;
reg    a_V_blk_n_B;
wire    ap_CS_fsm_state12;
reg    stream0_V_V_TDATA_blk_n;
wire    ap_CS_fsm_state1;
wire   [0:0] run_read_read_fu_192_p2;
wire   [0:0] bufstatus_load_phi_fu_853_p3;
wire   [0:0] tmp_nbreadreq_fu_204_p3;
reg    a_V_AWVALID;
wire    a_V_AWREADY;
reg    a_V_WVALID;
wire    a_V_WREADY;
wire    a_V_ARREADY;
wire    a_V_RVALID;
wire   [31:0] a_V_RDATA;
wire    a_V_RLAST;
wire   [0:0] a_V_RID;
wire   [0:0] a_V_RUSER;
wire   [1:0] a_V_RRESP;
wire    a_V_BVALID;
reg    a_V_BREADY;
wire   [1:0] a_V_BRESP;
wire   [0:0] a_V_BID;
wire   [0:0] a_V_BUSER;
reg   [12:0] indvar_reg_518;
reg   [31:0] DDROFFSET_V_read_reg_1297;
reg    ap_predicate_op81_read_state1;
reg    ap_block_state1;
reg   [0:0] run_read_reg_1302;
reg   [31:0] buffer_ack_read_reg_1306;
reg   [0:0] bufstatus_0_load_reg_1318;
reg   [0:0] bufstatus_1_load_reg_1325;
reg   [31:0] buftimeout_load_reg_1351;
reg   [0:0] bufsel_load_reg_1357;
wire   [63:0] tmp_3_fu_849_p1;
reg   [63:0] tmp_3_reg_1367;
reg   [0:0] bufstatus_load_phi_reg_1372;
reg   [0:0] swap_timeout_load_reg_1377;
reg   [31:0] buf_p_load_reg_1383;
reg   [0:0] tmp_reg_1390;
wire   [31:0] tmp_9_fu_885_p2;
wire   [0:0] tmp_5_fu_908_p2;
reg   [0:0] tmp_5_reg_1399;
wire   [63:0] tmp_6_fu_914_p2;
wire   [63:0] tmp_4_fu_926_p2;
wire   [0:0] brmerge_fu_943_p2;
reg   [0:0] brmerge_reg_1414;
wire    ap_CS_fsm_state3;
reg   [31:0] a_V_addr_reg_1418;
wire   [0:0] exitcond3_fu_1001_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
reg    ap_sig_ioackin_a_V_WREADY;
reg    ap_block_state7_io;
reg    ap_block_pp0_stage0_11001;
wire   [12:0] indvar_next_fu_1007_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [31:0] inbuffer_V_load_reg_1438;
reg    ap_enable_reg_pp0_iter1;
wire   [31:0] tmp_10_fu_1018_p2;
reg   [31:0] tmp_10_reg_1443;
wire    ap_CS_fsm_state11;
wire   [0:0] brmerge1_fu_1028_p2;
reg   [0:0] brmerge1_reg_1450;
wire   [0:0] not_bufsel_load_t_fu_1033_p2;
reg   [0:0] not_bufsel_load_t_reg_1454;
wire   [0:0] bufstatus_0_load_s_fu_1038_p2;
reg   [0:0] bufstatus_0_load_s_reg_1460;
wire   [0:0] p_bufstatus_1_load_fu_1043_p2;
reg   [0:0] p_bufstatus_1_load_reg_1465;
wire   [0:0] bufstatus_0_flag_2_fu_1146_p2;
reg   [0:0] bufstatus_0_flag_2_reg_1470;
wire    ap_CS_fsm_state14;
wire   [0:0] bufstatus_0_new_2_fu_1152_p2;
reg   [0:0] bufstatus_0_new_2_reg_1475;
wire   [0:0] bufstatus_1_flag_2_fu_1197_p2;
reg   [0:0] bufstatus_1_flag_2_reg_1480;
wire   [0:0] bufstatus_1_new_2_fu_1203_p2;
reg   [0:0] bufstatus_1_new_2_reg_1485;
reg    ap_sig_ioackin_a_V_AWREADY;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
reg   [0:0] inbuffer_pointer_fla_reg_430;
reg   [31:0] inbuffer_pointer_loc_reg_447;
reg   [63:0] out_counter_loc_reg_459;
reg   [63:0] lost_counter_loc_reg_471;
reg   [31:0] inbuffer_pointer_loc_1_reg_483;
reg   [63:0] out_counter_loc_1_reg_496;
reg   [63:0] lost_counter_loc_1_reg_507;
reg   [0:0] ap_phi_mux_bufstatus_0_flag_1_phi_fu_533_p6;
reg   [0:0] bufstatus_0_flag_1_reg_529;
reg   [0:0] ap_phi_mux_bufstatus_0_loc_1_phi_fu_546_p6;
reg   [0:0] bufstatus_0_loc_1_reg_543;
reg   [0:0] ap_phi_mux_bufstatus_1_flag_1_phi_fu_558_p6;
reg   [0:0] bufstatus_1_flag_1_reg_554;
reg   [0:0] ap_phi_mux_bufstatus_1_loc_1_phi_fu_571_p6;
reg   [0:0] bufstatus_1_loc_1_reg_568;
reg   [0:0] inbuffer_pointer_fla_1_reg_579;
reg   [31:0] inbuffer_pointer_new_1_reg_595;
reg   [63:0] out_counter_loc_2_reg_611;
reg   [63:0] lost_counter_loc_2_reg_627;
reg   [0:0] swap_timeout_flag_reg_643;
reg   [0:0] ap_phi_mux_buf_p_flag_phi_fu_664_p6;
reg   [0:0] buf_p_flag_reg_659;
reg   [31:0] ap_phi_mux_buf_p_loc_phi_fu_678_p6;
reg   [31:0] buf_p_loc_reg_675;
reg   [31:0] buftimeout_loc_reg_688;
reg   [0:0] ap_phi_mux_bufsel_load_3_phi_fu_704_p6;
reg   [0:0] bufsel_load_3_reg_701;
reg   [0:0] ap_phi_mux_bufstatus_0_flag_3_phi_fu_716_p4;
reg   [0:0] bufstatus_0_flag_3_reg_712;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state2;
reg   [0:0] ap_phi_mux_bufstatus_0_new_3_phi_fu_727_p4;
reg   [0:0] bufstatus_0_new_3_reg_723;
reg   [0:0] ap_phi_mux_bufstatus_1_flag_3_phi_fu_738_p4;
reg   [0:0] bufstatus_1_flag_3_reg_734;
reg   [0:0] ap_phi_mux_bufstatus_1_new_3_phi_fu_749_p4;
reg   [0:0] bufstatus_1_new_3_reg_745;
reg   [0:0] ap_phi_mux_inbuffer_pointer_fla_2_phi_fu_760_p4;
reg   [0:0] inbuffer_pointer_fla_2_reg_756;
reg   [31:0] ap_phi_mux_inbuffer_pointer_new_2_phi_fu_772_p4;
reg   [31:0] inbuffer_pointer_new_2_reg_768;
wire   [31:0] storemerge_fu_1258_p3;
reg   [31:0] ap_phi_mux_buftimeout_new_phi_fu_784_p4;
reg   [31:0] buftimeout_new_reg_780;
wire  signed [63:0] tmp_8_fu_875_p1;
wire  signed [63:0] tmp_s_fu_892_p1;
wire   [63:0] tmp_12_fu_1013_p1;
wire   [0:0] buffer_seq_addr_2_gep_fu_380_p3;
wire    ap_CS_fsm_state13;
wire   [0:0] buffer_seq_addr_3_gep_fu_389_p3;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire  signed [63:0] p_sum1_cast_fu_991_p1;
reg    ap_reg_ioackin_a_V_AWREADY;
reg    ap_reg_ioackin_a_V_WREADY;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_23_fu_1240_p2;
wire   [0:0] swap_timeout_flag_1_fu_1252_p2;
wire   [63:0] tmp_14_fu_1057_p2;
reg   [31:0] tmp_16_fu_1100_p4;
wire   [63:0] tmp_22_fu_1235_p1;
wire   [31:0] tmp_7_fu_869_p2;
wire   [0:0] swap_timeout_load_no_fu_938_p2;
wire   [29:0] tmp_1_fu_948_p4;
wire   [22:0] tmp_2_fu_964_p3;
wire   [30:0] tmp_11_cast_fu_971_p1;
wire   [30:0] op2_cast_fu_957_p1;
wire   [30:0] tmp3_fu_975_p2;
wire   [32:0] tmp3_cast_fu_981_p1;
wire  signed [32:0] tmp_2_cast_fu_961_p1;
wire   [32:0] p_sum1_fu_985_p2;
wire   [0:0] tmp_11_fu_1023_p2;
wire   [31:0] tmp_15_fu_1096_p1;
wire   [0:0] tmp_17_fu_1115_p1;
wire   [0:0] tmp_25_fu_1131_p1;
wire   [0:0] tmp_18_fu_1119_p2;
wire   [0:0] bufstatus_0_flag_1_s_fu_1140_p2;
wire   [0:0] tmp_19_fu_1134_p2;
wire   [0:0] tmp_26_fu_1164_p3;
wire   [0:0] tmp_27_fu_1178_p3;
wire   [0:0] rev_fu_1172_p2;
wire   [0:0] bufstatus_1_flag_1_s_fu_1191_p2;
wire   [0:0] rev8_fu_1185_p2;
wire   [0:0] bufstatus_load_4_fu_1158_p2;
wire   [31:0] tmp_20_fu_1220_p1;
wire   [0:0] bufstatus_load_5_fu_1209_p2;
wire   [31:0] tmp_24_fu_1246_p2;
reg   [14:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_307;

// power-on initialization
initial begin
#0 bufstatus_0 = 1'd0;
#0 bufstatus_1 = 1'd0;
#0 inbuffer_pointer = 32'd0;
#0 out_counter = 64'd0;
#0 lost_counter = 64'd0;
#0 buftimeout = 32'd0;
#0 bufsel = 1'd0;
#0 swap_timeout = 1'd0;
#0 buf_p = 32'd0;
#0 bsc = 64'd0;
#0 bsq_0 = 64'd0;
#0 bsq_1 = 64'd0;
#0 obuffer_ack = 32'd0;
#0 ap_CS_fsm = 15'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_reg_ioackin_a_V_AWREADY = 1'b0;
#0 ap_reg_ioackin_a_V_WREADY = 1'b0;
end

data_mover_inbuffbkb #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
inbuffer_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inbuffer_V_address0),
    .ce0(inbuffer_V_ce0),
    .we0(inbuffer_V_we0),
    .d0(inbuffer_V_d0),
    .q0(inbuffer_V_q0),
    .address1(inbuffer_V_address1),
    .ce1(inbuffer_V_ce1),
    .we1(inbuffer_V_we1),
    .d1(inbuffer_V_d1)
);

data_mover_axil_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXIL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXIL_DATA_WIDTH ))
data_mover_axil_s_axi_U(
    .AWVALID(s_axi_axil_AWVALID),
    .AWREADY(s_axi_axil_AWREADY),
    .AWADDR(s_axi_axil_AWADDR),
    .WVALID(s_axi_axil_WVALID),
    .WREADY(s_axi_axil_WREADY),
    .WDATA(s_axi_axil_WDATA),
    .WSTRB(s_axi_axil_WSTRB),
    .ARVALID(s_axi_axil_ARVALID),
    .ARREADY(s_axi_axil_ARREADY),
    .ARADDR(s_axi_axil_ARADDR),
    .RVALID(s_axi_axil_RVALID),
    .RREADY(s_axi_axil_RREADY),
    .RDATA(s_axi_axil_RDATA),
    .RRESP(s_axi_axil_RRESP),
    .BVALID(s_axi_axil_BVALID),
    .BREADY(s_axi_axil_BREADY),
    .BRESP(s_axi_axil_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .buffer_status(buffer_status),
    .buffer_status_ap_vld(buffer_status_ap_vld),
    .buffer_ack(buffer_ack),
    .buffer_seq_address0(buffer_seq_address0),
    .buffer_seq_ce0(buffer_seq_ce0),
    .buffer_seq_we0(buffer_seq_we0),
    .buffer_seq_d0(buffer_seq_d0),
    .bufsize_address0(bufsize_address0),
    .bufsize_ce0(bufsize_ce0),
    .bufsize_we0(bufsize_we0),
    .bufsize_d0(bufsize_d0),
    .run(run),
    .DDROFFSET_V(DDROFFSET_V),
    .stat_counter_address0(stat_counter_address0),
    .stat_counter_ce0(stat_counter_ce0),
    .stat_counter_we0(stat_counter_we0),
    .stat_counter_d0(stat_counter_d0)
);

data_mover_a_V_m_axi #(
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_A_V_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_A_V_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_A_V_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_A_V_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_A_V_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_A_V_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_A_V_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_A_V_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_A_V_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_A_V_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_A_V_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_A_V_CACHE_VALUE ))
data_mover_a_V_m_axi_U(
    .AWVALID(m_axi_a_V_AWVALID),
    .AWREADY(m_axi_a_V_AWREADY),
    .AWADDR(m_axi_a_V_AWADDR),
    .AWID(m_axi_a_V_AWID),
    .AWLEN(m_axi_a_V_AWLEN),
    .AWSIZE(m_axi_a_V_AWSIZE),
    .AWBURST(m_axi_a_V_AWBURST),
    .AWLOCK(m_axi_a_V_AWLOCK),
    .AWCACHE(m_axi_a_V_AWCACHE),
    .AWPROT(m_axi_a_V_AWPROT),
    .AWQOS(m_axi_a_V_AWQOS),
    .AWREGION(m_axi_a_V_AWREGION),
    .AWUSER(m_axi_a_V_AWUSER),
    .WVALID(m_axi_a_V_WVALID),
    .WREADY(m_axi_a_V_WREADY),
    .WDATA(m_axi_a_V_WDATA),
    .WSTRB(m_axi_a_V_WSTRB),
    .WLAST(m_axi_a_V_WLAST),
    .WID(m_axi_a_V_WID),
    .WUSER(m_axi_a_V_WUSER),
    .ARVALID(m_axi_a_V_ARVALID),
    .ARREADY(m_axi_a_V_ARREADY),
    .ARADDR(m_axi_a_V_ARADDR),
    .ARID(m_axi_a_V_ARID),
    .ARLEN(m_axi_a_V_ARLEN),
    .ARSIZE(m_axi_a_V_ARSIZE),
    .ARBURST(m_axi_a_V_ARBURST),
    .ARLOCK(m_axi_a_V_ARLOCK),
    .ARCACHE(m_axi_a_V_ARCACHE),
    .ARPROT(m_axi_a_V_ARPROT),
    .ARQOS(m_axi_a_V_ARQOS),
    .ARREGION(m_axi_a_V_ARREGION),
    .ARUSER(m_axi_a_V_ARUSER),
    .RVALID(m_axi_a_V_RVALID),
    .RREADY(m_axi_a_V_RREADY),
    .RDATA(m_axi_a_V_RDATA),
    .RLAST(m_axi_a_V_RLAST),
    .RID(m_axi_a_V_RID),
    .RUSER(m_axi_a_V_RUSER),
    .RRESP(m_axi_a_V_RRESP),
    .BVALID(m_axi_a_V_BVALID),
    .BREADY(m_axi_a_V_BREADY),
    .BRESP(m_axi_a_V_BRESP),
    .BID(m_axi_a_V_BID),
    .BUSER(m_axi_a_V_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(a_V_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(a_V_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(a_V_RDATA),
    .I_RID(a_V_RID),
    .I_RUSER(a_V_RUSER),
    .I_RRESP(a_V_RRESP),
    .I_RLAST(a_V_RLAST),
    .I_AWVALID(a_V_AWVALID),
    .I_AWREADY(a_V_AWREADY),
    .I_AWADDR(a_V_addr_reg_1418),
    .I_AWID(1'd0),
    .I_AWLEN(32'd4096),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(a_V_WVALID),
    .I_WREADY(a_V_WREADY),
    .I_WDATA(inbuffer_V_load_reg_1438),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(a_V_BVALID),
    .I_BREADY(a_V_BREADY),
    .I_BRESP(a_V_BRESP),
    .I_BID(a_V_BID),
    .I_BUSER(a_V_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_sig_ioackin_a_V_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state5)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_sig_ioackin_a_V_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_a_V_AWREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            if ((ap_sig_ioackin_a_V_AWREADY == 1'b1)) begin
                ap_reg_ioackin_a_V_AWREADY <= 1'b0;
            end else if ((1'b1 == a_V_AWREADY)) begin
                ap_reg_ioackin_a_V_AWREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_a_V_WREADY <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_exitcond3_reg_1424 == 1'd0))) begin
            if ((1'b0 == ap_block_pp0_stage0_11001)) begin
                ap_reg_ioackin_a_V_WREADY <= 1'b0;
            end else if (((1'b0 == ap_block_pp0_stage0_01001) & (1'b1 == a_V_WREADY))) begin
                ap_reg_ioackin_a_V_WREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd1))) begin
        bsc <= tmp_14_fu_1057_p2;
    end else if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd0))) begin
        bsc <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        buf_p_flag_reg_659 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1))))) begin
        buf_p_flag_reg_659 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0))) begin
        buf_p_loc_reg_675 <= tmp_10_reg_1443;
    end else if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        buf_p_loc_reg_675 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1))))) begin
        buf_p_loc_reg_675 <= buf_p_load_reg_1383;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd1))) begin
        bufsel <= not_bufsel_load_t_fu_1033_p2;
    end else if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd0))) begin
        bufsel <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        bufsel_load_3_reg_701 <= not_bufsel_load_t_reg_1454;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        bufsel_load_3_reg_701 <= bufsel_load_reg_1357;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        bufstatus_0_flag_1_reg_529 <= not_bufsel_load_t_reg_1454;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        bufstatus_0_flag_1_reg_529 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bufstatus_0_flag_3_reg_712 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        bufstatus_0_flag_3_reg_712 <= bufstatus_0_flag_2_reg_1470;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        bufstatus_0_loc_1_reg_543 <= bufstatus_0_load_s_reg_1460;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        bufstatus_0_loc_1_reg_543 <= bufstatus_0_load_reg_1318;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bufstatus_0_new_3_reg_723 <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        bufstatus_0_new_3_reg_723 <= bufstatus_0_new_2_reg_1475;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        bufstatus_1_flag_1_reg_554 <= bufsel_load_reg_1357;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        bufstatus_1_flag_1_reg_554 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bufstatus_1_flag_3_reg_734 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        bufstatus_1_flag_3_reg_734 <= bufstatus_1_flag_2_reg_1480;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        bufstatus_1_loc_1_reg_568 <= p_bufstatus_1_load_reg_1465;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        bufstatus_1_loc_1_reg_568 <= bufstatus_1_load_reg_1325;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bufstatus_1_new_3_reg_745 <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        bufstatus_1_new_3_reg_745 <= bufstatus_1_new_2_reg_1485;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        buftimeout_loc_reg_688 <= 32'd0;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        buftimeout_loc_reg_688 <= buftimeout_load_reg_1351;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        buftimeout_new_reg_780 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        buftimeout_new_reg_780 <= storemerge_fu_1258_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        inbuffer_pointer_fla_1_reg_579 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1))))) begin
        inbuffer_pointer_fla_1_reg_579 <= inbuffer_pointer_fla_reg_430;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        inbuffer_pointer_fla_2_reg_756 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        inbuffer_pointer_fla_2_reg_756 <= inbuffer_pointer_fla_1_reg_579;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_204_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1) & (tmp_5_fu_908_p2 == 1'd0) & (bufstatus_load_phi_fu_853_p3 == 1'd0))) begin
        inbuffer_pointer_fla_reg_430 <= 1'd1;
    end else if (((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (bufstatus_load_phi_fu_853_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1)) | (~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd0) & (bufstatus_load_phi_fu_853_p3 == 1'd0)))) begin
        inbuffer_pointer_fla_reg_430 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (tmp_5_fu_908_p2 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1) & (bufstatus_load_phi_fu_853_p3 == 1'd0))) begin
        inbuffer_pointer_loc_1_reg_483 <= 32'd4096;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd0) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd0) & (tmp_reg_1390 == 1'd0)) | ((bufstatus_load_phi_reg_1372 == 1'd1) & (brmerge_fu_943_p2 == 1'd0))))) begin
        inbuffer_pointer_loc_1_reg_483 <= inbuffer_pointer_loc_reg_447;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_204_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1) & (tmp_5_fu_908_p2 == 1'd0) & (bufstatus_load_phi_fu_853_p3 == 1'd0))) begin
        inbuffer_pointer_loc_reg_447 <= tmp_9_fu_885_p2;
    end else if (((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (bufstatus_load_phi_fu_853_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1)) | (~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd0) & (bufstatus_load_phi_fu_853_p3 == 1'd0)))) begin
        inbuffer_pointer_loc_reg_447 <= inbuffer_pointer;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        inbuffer_pointer_new_1_reg_595 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1))))) begin
        inbuffer_pointer_new_1_reg_595 <= inbuffer_pointer_loc_reg_447;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        inbuffer_pointer_new_2_reg_768 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        inbuffer_pointer_new_2_reg_768 <= inbuffer_pointer_new_1_reg_595;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond3_fu_1001_p2 == 1'd0))) begin
        indvar_reg_518 <= indvar_next_fu_1007_p2;
    end else if (((ap_sig_ioackin_a_V_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        indvar_reg_518 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_307)) begin
        if (((bufstatus_load_phi_fu_853_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1))) begin
            lost_counter <= tmp_4_fu_926_p2;
        end else if ((run_read_read_fu_192_p2 == 1'd0)) begin
            lost_counter <= 64'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (tmp_5_fu_908_p2 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1) & (bufstatus_load_phi_fu_853_p3 == 1'd0))) begin
        lost_counter_loc_1_reg_507 <= lost_counter;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd0) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd0) & (tmp_reg_1390 == 1'd0)) | ((bufstatus_load_phi_reg_1372 == 1'd1) & (brmerge_fu_943_p2 == 1'd0))))) begin
        lost_counter_loc_1_reg_507 <= lost_counter_loc_reg_471;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        lost_counter_loc_2_reg_627 <= lost_counter_loc_1_reg_507;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1))))) begin
        lost_counter_loc_2_reg_627 <= lost_counter_loc_reg_471;
    end
end

always @ (posedge ap_clk) begin
    if (((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd0) & (bufstatus_load_phi_fu_853_p3 == 1'd0)) | (~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_204_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1) & (tmp_5_fu_908_p2 == 1'd0) & (bufstatus_load_phi_fu_853_p3 == 1'd0)))) begin
        lost_counter_loc_reg_471 <= lost_counter;
    end else if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (bufstatus_load_phi_fu_853_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1))) begin
        lost_counter_loc_reg_471 <= tmp_4_fu_926_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        obuffer_ack <= buffer_ack_read_reg_1306;
    end else if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd0))) begin
        obuffer_ack <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_307)) begin
        if ((ap_predicate_op81_read_state1 == 1'b1)) begin
            out_counter <= tmp_6_fu_914_p2;
        end else if ((run_read_read_fu_192_p2 == 1'd0)) begin
            out_counter <= 64'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (tmp_5_fu_908_p2 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1) & (bufstatus_load_phi_fu_853_p3 == 1'd0))) begin
        out_counter_loc_1_reg_496 <= tmp_6_fu_914_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd0) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd0) & (tmp_reg_1390 == 1'd0)) | ((bufstatus_load_phi_reg_1372 == 1'd1) & (brmerge_fu_943_p2 == 1'd0))))) begin
        out_counter_loc_1_reg_496 <= out_counter_loc_reg_459;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        out_counter_loc_2_reg_611 <= out_counter_loc_1_reg_496;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1))))) begin
        out_counter_loc_2_reg_611 <= out_counter_loc_reg_459;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_204_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1) & (tmp_5_fu_908_p2 == 1'd0) & (bufstatus_load_phi_fu_853_p3 == 1'd0))) begin
        out_counter_loc_reg_459 <= tmp_6_fu_914_p2;
    end else if (((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (bufstatus_load_phi_fu_853_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1)) | (~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd0) & (bufstatus_load_phi_fu_853_p3 == 1'd0)))) begin
        out_counter_loc_reg_459 <= out_counter;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        swap_timeout_flag_reg_643 <= 1'd1;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1)))) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0)))) begin
        swap_timeout_flag_reg_643 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DDROFFSET_V_read_reg_1297 <= DDROFFSET_V;
        buffer_ack_read_reg_1306 <= buffer_ack;
        bufstatus_0_load_reg_1318 <= bufstatus_0;
        bufstatus_1_load_reg_1325 <= bufstatus_1;
        buftimeout_load_reg_1351 <= buftimeout;
        run_read_reg_1302 <= run;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((brmerge_fu_943_p2 == 1'd0) | ((tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        a_V_addr_reg_1418 <= p_sum1_cast_fu_991_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_reg_pp0_iter1_exitcond3_reg_1424 <= exitcond3_reg_1424;
        exitcond3_reg_1424 <= exitcond3_fu_1001_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12))) begin
        brmerge1_reg_1450 <= brmerge1_fu_1028_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((bufstatus_load_phi_reg_1372 == 1'd1) | (tmp_5_reg_1399 == 1'd0) | (tmp_reg_1390 == 1'd0)))) begin
        brmerge_reg_1414 <= brmerge_fu_943_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd1) & (bufsel_load_reg_1357 == 1'd1))) begin
        bsq_0 <= tmp_14_fu_1057_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd1) & (bufsel_load_reg_1357 == 1'd0))) begin
        bsq_1 <= tmp_14_fu_1057_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (ap_phi_mux_buf_p_flag_phi_fu_664_p6 == 1'd1))) begin
        buf_p <= ap_phi_mux_buf_p_loc_phi_fu_678_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd1))) begin
        buf_p_load_reg_1383 <= buf_p;
        bufsel_load_reg_1357 <= bufsel;
        bufstatus_load_phi_reg_1372 <= bufstatus_load_phi_fu_853_p3;
        swap_timeout_load_reg_1377 <= swap_timeout;
        tmp_3_reg_1367[0] <= tmp_3_fu_849_p1[0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (ap_phi_mux_bufstatus_0_flag_3_phi_fu_716_p4 == 1'd1))) begin
        bufstatus_0 <= ap_phi_mux_bufstatus_0_new_3_phi_fu_727_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        bufstatus_0_flag_2_reg_1470 <= bufstatus_0_flag_2_fu_1146_p2;
        bufstatus_0_new_2_reg_1475 <= bufstatus_0_new_2_fu_1152_p2;
        bufstatus_1_flag_2_reg_1480 <= bufstatus_1_flag_2_fu_1197_p2;
        bufstatus_1_new_2_reg_1485 <= bufstatus_1_new_2_fu_1203_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd1))) begin
        bufstatus_0_load_s_reg_1460 <= bufstatus_0_load_s_fu_1038_p2;
        not_bufsel_load_t_reg_1454 <= not_bufsel_load_t_fu_1033_p2;
        p_bufstatus_1_load_reg_1465 <= p_bufstatus_1_load_fu_1043_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (ap_phi_mux_bufstatus_1_flag_3_phi_fu_738_p4 == 1'd1))) begin
        bufstatus_1 <= ap_phi_mux_bufstatus_1_new_3_phi_fu_749_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        buftimeout <= ap_phi_mux_buftimeout_new_phi_fu_784_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond3_reg_1424 == 1'd0))) begin
        inbuffer_V_load_reg_1438 <= inbuffer_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (ap_phi_mux_inbuffer_pointer_fla_2_phi_fu_760_p4 == 1'd1))) begin
        inbuffer_pointer <= ap_phi_mux_inbuffer_pointer_new_2_phi_fu_772_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (swap_timeout_flag_1_fu_1252_p2 == 1'd1) & (run_read_reg_1302 == 1'd1))) begin
        swap_timeout <= tmp_23_fu_1240_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        tmp_10_reg_1443 <= tmp_10_fu_1018_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op81_read_state1 == 1'b1))) begin
        tmp_5_reg_1399 <= tmp_5_fu_908_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd1) & (bufstatus_load_phi_fu_853_p3 == 1'd0))) begin
        tmp_reg_1390 <= stream0_V_V_TVALID;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_a_V_AWREADY == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        a_V_AWVALID = 1'b1;
    end else begin
        a_V_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12))) begin
        a_V_BREADY = 1'b1;
    end else begin
        a_V_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_reg_ioackin_a_V_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_exitcond3_reg_1424 == 1'd0))) begin
        a_V_WVALID = 1'b1;
    end else begin
        a_V_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        a_V_blk_n_AW = m_axi_a_V_AWREADY;
    end else begin
        a_V_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        a_V_blk_n_B = m_axi_a_V_BVALID;
    end else begin
        a_V_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_reg_pp0_iter1_exitcond3_reg_1424 == 1'd0))) begin
        a_V_blk_n_W = m_axi_a_V_WREADY;
    end else begin
        a_V_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((exitcond3_fu_1001_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        ap_phi_mux_buf_p_flag_phi_fu_664_p6 = 1'd1;
    end else begin
        ap_phi_mux_buf_p_flag_phi_fu_664_p6 = buf_p_flag_reg_659;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        ap_phi_mux_buf_p_loc_phi_fu_678_p6 = 32'd0;
    end else begin
        ap_phi_mux_buf_p_loc_phi_fu_678_p6 = buf_p_loc_reg_675;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        ap_phi_mux_bufsel_load_3_phi_fu_704_p6 = not_bufsel_load_t_reg_1454;
    end else begin
        ap_phi_mux_bufsel_load_3_phi_fu_704_p6 = bufsel_load_3_reg_701;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        ap_phi_mux_bufstatus_0_flag_1_phi_fu_533_p6 = not_bufsel_load_t_reg_1454;
    end else begin
        ap_phi_mux_bufstatus_0_flag_1_phi_fu_533_p6 = bufstatus_0_flag_1_reg_529;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        ap_phi_mux_bufstatus_0_flag_3_phi_fu_716_p4 = bufstatus_0_flag_2_reg_1470;
    end else begin
        ap_phi_mux_bufstatus_0_flag_3_phi_fu_716_p4 = bufstatus_0_flag_3_reg_712;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        ap_phi_mux_bufstatus_0_loc_1_phi_fu_546_p6 = bufstatus_0_load_s_reg_1460;
    end else begin
        ap_phi_mux_bufstatus_0_loc_1_phi_fu_546_p6 = bufstatus_0_loc_1_reg_543;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        ap_phi_mux_bufstatus_0_new_3_phi_fu_727_p4 = bufstatus_0_new_2_reg_1475;
    end else begin
        ap_phi_mux_bufstatus_0_new_3_phi_fu_727_p4 = bufstatus_0_new_3_reg_723;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        ap_phi_mux_bufstatus_1_flag_1_phi_fu_558_p6 = bufsel_load_reg_1357;
    end else begin
        ap_phi_mux_bufstatus_1_flag_1_phi_fu_558_p6 = bufstatus_1_flag_1_reg_554;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        ap_phi_mux_bufstatus_1_flag_3_phi_fu_738_p4 = bufstatus_1_flag_2_reg_1480;
    end else begin
        ap_phi_mux_bufstatus_1_flag_3_phi_fu_738_p4 = bufstatus_1_flag_3_reg_734;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        ap_phi_mux_bufstatus_1_loc_1_phi_fu_571_p6 = p_bufstatus_1_load_reg_1465;
    end else begin
        ap_phi_mux_bufstatus_1_loc_1_phi_fu_571_p6 = bufstatus_1_loc_1_reg_568;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        ap_phi_mux_bufstatus_1_new_3_phi_fu_749_p4 = bufstatus_1_new_2_reg_1485;
    end else begin
        ap_phi_mux_bufstatus_1_new_3_phi_fu_749_p4 = bufstatus_1_new_3_reg_745;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        ap_phi_mux_buftimeout_new_phi_fu_784_p4 = storemerge_fu_1258_p3;
    end else begin
        ap_phi_mux_buftimeout_new_phi_fu_784_p4 = buftimeout_new_reg_780;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        ap_phi_mux_inbuffer_pointer_fla_2_phi_fu_760_p4 = inbuffer_pointer_fla_1_reg_579;
    end else begin
        ap_phi_mux_inbuffer_pointer_fla_2_phi_fu_760_p4 = inbuffer_pointer_fla_2_reg_756;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1))) begin
        ap_phi_mux_inbuffer_pointer_new_2_phi_fu_772_p4 = inbuffer_pointer_new_1_reg_595;
    end else begin
        ap_phi_mux_inbuffer_pointer_new_2_phi_fu_772_p4 = inbuffer_pointer_new_2_reg_768;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_a_V_AWREADY == 1'b0)) begin
        ap_sig_ioackin_a_V_AWREADY = a_V_AWREADY;
    end else begin
        ap_sig_ioackin_a_V_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_a_V_WREADY == 1'b0)) begin
        ap_sig_ioackin_a_V_WREADY = a_V_WREADY;
    end else begin
        ap_sig_ioackin_a_V_WREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        buffer_seq_address0 = buffer_seq_addr_3_gep_fu_389_p3;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        buffer_seq_address0 = buffer_seq_addr_2_gep_fu_380_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buffer_seq_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        buffer_seq_address0 = 64'd0;
    end else begin
        buffer_seq_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state14) | (~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        buffer_seq_ce0 = 1'b1;
    end else begin
        buffer_seq_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        buffer_seq_d0 = bsq_1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        buffer_seq_d0 = bsq_0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        buffer_seq_d0 = 64'd0;
    end else begin
        buffer_seq_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0)))) | (~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd0)))) begin
        buffer_seq_we0 = 1'b1;
    end else begin
        buffer_seq_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        buffer_status = tmp_16_fu_1100_p4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buffer_status = 32'd0;
    end else begin
        buffer_status = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state14))) begin
        buffer_status_ap_vld = 1'b1;
    end else begin
        buffer_status_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        bufsize_address0 = tmp_3_reg_1367;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        bufsize_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        bufsize_address0 = 64'd0;
    end else begin
        bufsize_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12)))) begin
        bufsize_ce0 = 1'b1;
    end else begin
        bufsize_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        bufsize_d0 = tmp_10_reg_1443;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        bufsize_d0 = 32'd0;
    end else begin
        bufsize_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd0)) | ((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd1)))) begin
        bufsize_we0 = 1'b1;
    end else begin
        bufsize_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        debug_buf0_p_ap_vld = 1'b1;
    end else begin
        debug_buf0_p_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        debug_buffer_status_ap_vld = 1'b1;
    end else begin
        debug_buffer_status_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        debug_bufsel_0_ap_vld = 1'b1;
    end else begin
        debug_bufsel_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op81_read_state1 == 1'b1))) begin
        debug_dst_var_V_ap_vld = 1'b1;
    end else begin
        debug_dst_var_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op81_read_state1 == 1'b1))) begin
        debug_inbuffer_pointer_ap_vld = 1'b1;
    end else begin
        debug_inbuffer_pointer_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inbuffer_V_address0 = tmp_12_fu_1013_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        inbuffer_V_address0 = tmp_8_fu_875_p1;
    end else begin
        inbuffer_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        inbuffer_V_ce0 = 1'b1;
    end else begin
        inbuffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        inbuffer_V_ce1 = 1'b1;
    end else begin
        inbuffer_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op81_read_state1 == 1'b1))) begin
        inbuffer_V_we0 = 1'b1;
    end else begin
        inbuffer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op81_read_state1 == 1'b1))) begin
        inbuffer_V_we1 = 1'b1;
    end else begin
        inbuffer_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0))))) begin
        interrupt_r = 1'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        interrupt_r = 1'd0;
    end else begin
        interrupt_r = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state14) & (((brmerge1_reg_1450 == 1'd1) & (brmerge_reg_1414 == 1'd0)) | ((brmerge1_reg_1450 == 1'd1) & (tmp_5_reg_1399 == 1'd1) & (tmp_reg_1390 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd0)))))) begin
        interrupt_r_ap_vld = 1'b1;
    end else begin
        interrupt_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        stat_counter_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        stat_counter_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        stat_counter_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        stat_counter_address0 = 64'd0;
    end else begin
        stat_counter_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state14))) begin
        stat_counter_ce0 = 1'b1;
    end else begin
        stat_counter_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        stat_counter_d0 = tmp_22_fu_1235_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        stat_counter_d0 = lost_counter_loc_2_reg_627;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        stat_counter_d0 = out_counter_loc_2_reg_611;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        stat_counter_d0 = 64'd0;
    end else begin
        stat_counter_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state17) & (run_read_reg_1302 == 1'd1)))) begin
        stat_counter_we0 = 1'b1;
    end else begin
        stat_counter_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_204_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1) & (bufstatus_load_phi_fu_853_p3 == 1'd0))) begin
        stream0_V_V_TDATA_blk_n = stream0_V_V_TVALID;
    end else begin
        stream0_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op81_read_state1 == 1'b1))) begin
        stream0_V_V_TREADY = 1'b1;
    end else begin
        stream0_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (run_read_read_fu_192_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (((brmerge_fu_943_p2 == 1'd1) & (tmp_5_reg_1399 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (tmp_reg_1390 == 1'd0)) | ((brmerge_fu_943_p2 == 1'd1) & (bufstatus_load_phi_reg_1372 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((ap_sig_ioackin_a_V_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond3_fu_1001_p2 == 1'd1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond3_fu_1001_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((1'b1 == a_V_BVALID) & (1'b1 == ap_CS_fsm_state12) & (brmerge1_fu_1028_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state7_io));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state7_io));
end

always @ (*) begin
    ap_block_state1 = ((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_io = ((ap_sig_ioackin_a_V_WREADY == 1'b0) & (ap_reg_pp0_iter1_exitcond3_reg_1424 == 1'd0));
end

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_307 = (~((stream0_V_V_TVALID == 1'b0) & (ap_predicate_op81_read_state1 == 1'b1)) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op81_read_state1 = ((tmp_nbreadreq_fu_204_p3 == 1'd1) & (run_read_read_fu_192_p2 == 1'd1) & (bufstatus_load_phi_fu_853_p3 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign brmerge1_fu_1028_p2 = (tmp_11_fu_1023_p2 | swap_timeout_load_reg_1377);

assign brmerge_fu_943_p2 = (swap_timeout_load_no_fu_938_p2 | bufstatus_load_phi_reg_1372);

assign buffer_seq_addr_2_gep_fu_380_p3 = 64'd0;

assign buffer_seq_addr_3_gep_fu_389_p3 = 64'd1;

assign bufstatus_0_flag_1_s_fu_1140_p2 = (tmp_25_fu_1131_p1 & tmp_18_fu_1119_p2);

assign bufstatus_0_flag_2_fu_1146_p2 = (bufstatus_0_flag_1_s_fu_1140_p2 | ap_phi_mux_bufstatus_0_flag_1_phi_fu_533_p6);

assign bufstatus_0_load_s_fu_1038_p2 = (not_bufsel_load_t_fu_1033_p2 | bufstatus_0_load_reg_1318);

assign bufstatus_0_new_2_fu_1152_p2 = (tmp_19_fu_1134_p2 | tmp_17_fu_1115_p1);

assign bufstatus_1_flag_1_s_fu_1191_p2 = (tmp_27_fu_1178_p3 & rev_fu_1172_p2);

assign bufstatus_1_flag_2_fu_1197_p2 = (bufstatus_1_flag_1_s_fu_1191_p2 | ap_phi_mux_bufstatus_1_flag_1_phi_fu_558_p6);

assign bufstatus_1_new_2_fu_1203_p2 = (tmp_26_fu_1164_p3 | rev8_fu_1185_p2);

assign bufstatus_load_4_fu_1158_p2 = (bufstatus_0_new_2_fu_1152_p2 & ap_phi_mux_bufstatus_0_loc_1_phi_fu_546_p6);

assign bufstatus_load_5_fu_1209_p2 = (bufstatus_1_new_2_fu_1203_p2 & ap_phi_mux_bufstatus_1_loc_1_phi_fu_571_p6);

assign bufstatus_load_phi_fu_853_p3 = ((bufsel[0:0] === 1'b1) ? bufstatus_1 : bufstatus_0);

assign debug_buf0_p = ap_phi_mux_buf_p_loc_phi_fu_678_p6;

always @ (*) begin
    debug_buffer_status = tmp_20_fu_1220_p1;
    debug_buffer_status[32'd1] = |(bufstatus_load_5_fu_1209_p2);
end

assign debug_bufsel_0 = ap_phi_mux_bufsel_load_3_phi_fu_704_p6;

assign debug_dst_var_V = stream0_V_V_TDATA;

assign debug_inbuffer_pointer = tmp_9_fu_885_p2;

assign exitcond3_fu_1001_p2 = ((indvar_reg_518 == 13'd4096) ? 1'b1 : 1'b0);

assign inbuffer_V_address1 = tmp_s_fu_892_p1;

assign inbuffer_V_d0 = stream0_V_V_TDATA[31:0];

assign inbuffer_V_d1 = {{stream0_V_V_TDATA[63:32]}};

assign indvar_next_fu_1007_p2 = (indvar_reg_518 + 13'd1);

assign not_bufsel_load_t_fu_1033_p2 = (bufsel_load_reg_1357 ^ 1'd1);

assign op2_cast_fu_957_p1 = tmp_1_fu_948_p4;

assign p_bufstatus_1_load_fu_1043_p2 = (bufstatus_1_load_reg_1325 | bufsel_load_reg_1357);

assign p_sum1_cast_fu_991_p1 = $signed(p_sum1_fu_985_p2);

assign p_sum1_fu_985_p2 = ($signed(tmp3_cast_fu_981_p1) + $signed(tmp_2_cast_fu_961_p1));

assign rev8_fu_1185_p2 = (tmp_27_fu_1178_p3 ^ 1'd1);

assign rev_fu_1172_p2 = (tmp_26_fu_1164_p3 ^ 1'd1);

assign run_read_read_fu_192_p2 = run;

assign storemerge_fu_1258_p3 = ((tmp_23_fu_1240_p2[0:0] === 1'b1) ? 32'd0 : tmp_24_fu_1246_p2);

assign swap_timeout_flag_1_fu_1252_p2 = (tmp_23_fu_1240_p2 | swap_timeout_flag_reg_643);

assign swap_timeout_load_no_fu_938_p2 = (swap_timeout_load_reg_1377 ^ 1'd1);

assign tmp3_cast_fu_981_p1 = tmp3_fu_975_p2;

assign tmp3_fu_975_p2 = (tmp_11_cast_fu_971_p1 + op2_cast_fu_957_p1);

assign tmp_10_fu_1018_p2 = (buf_p_load_reg_1383 + inbuffer_pointer_loc_1_reg_483);

assign tmp_11_cast_fu_971_p1 = tmp_2_fu_964_p3;

assign tmp_11_fu_1023_p2 = ((tmp_10_reg_1443 == 32'd4194304) ? 1'b1 : 1'b0);

assign tmp_12_fu_1013_p1 = indvar_reg_518;

assign tmp_14_fu_1057_p2 = (bsc + 64'd1);

assign tmp_15_fu_1096_p1 = ap_phi_mux_bufstatus_0_loc_1_phi_fu_546_p6;

always @ (*) begin
    tmp_16_fu_1100_p4 = tmp_15_fu_1096_p1;
    tmp_16_fu_1100_p4[32'd1] = |(ap_phi_mux_bufstatus_1_loc_1_phi_fu_571_p6);
end

assign tmp_17_fu_1115_p1 = obuffer_ack[0:0];

assign tmp_18_fu_1119_p2 = (tmp_17_fu_1115_p1 ^ 1'd1);

assign tmp_19_fu_1134_p2 = (tmp_25_fu_1131_p1 ^ 1'd1);

assign tmp_1_fu_948_p4 = {{DDROFFSET_V_read_reg_1297[31:2]}};

assign tmp_20_fu_1220_p1 = bufstatus_load_4_fu_1158_p2;

assign tmp_22_fu_1235_p1 = buftimeout_loc_reg_688;

assign tmp_23_fu_1240_p2 = ((buftimeout_loc_reg_688 == 32'd10000000) ? 1'b1 : 1'b0);

assign tmp_24_fu_1246_p2 = (32'd1 + buftimeout_loc_reg_688);

assign tmp_25_fu_1131_p1 = buffer_ack_read_reg_1306[0:0];

assign tmp_26_fu_1164_p3 = obuffer_ack[32'd1];

assign tmp_27_fu_1178_p3 = buffer_ack_read_reg_1306[32'd1];

assign tmp_2_cast_fu_961_p1 = $signed(buf_p_load_reg_1383);

assign tmp_2_fu_964_p3 = {{bufsel_load_reg_1357}, {22'd0}};

assign tmp_3_fu_849_p1 = bufsel;

assign tmp_4_fu_926_p2 = (lost_counter + 64'd1);

assign tmp_5_fu_908_p2 = ((tmp_9_fu_885_p2 == 32'd4096) ? 1'b1 : 1'b0);

assign tmp_6_fu_914_p2 = (64'd1 + out_counter);

assign tmp_7_fu_869_p2 = (32'd1 + inbuffer_pointer);

assign tmp_8_fu_875_p1 = $signed(inbuffer_pointer);

assign tmp_9_fu_885_p2 = (32'd2 + inbuffer_pointer);

assign tmp_nbreadreq_fu_204_p3 = stream0_V_V_TVALID;

assign tmp_s_fu_892_p1 = $signed(tmp_7_fu_869_p2);

always @ (posedge ap_clk) begin
    tmp_3_reg_1367[63:1] <= 63'b000000000000000000000000000000000000000000000000000000000000000;
end

endmodule //data_mover
