# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/OpenHardware/NuclearOption/asdf/output/asdf/asdf.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_FS_0_AXIFIFO_0/ZynqDesign_FS_0_AXIFIFO_0.xci
# IP: The module: 'ZynqDesign_FS_0_AXIFIFO_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/OpenHardware/NuclearOption/asdf/output/asdf/asdf.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_FS_0_AXIFIFO_0/ZynqDesign_FS_0_AXIFIFO_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqDesign_FS_0_AXIFIFO_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/OpenHardware/NuclearOption/asdf/output/asdf/asdf.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_FS_0_AXIFIFO_0/ZynqDesign_FS_0_AXIFIFO_0/ZynqDesign_FS_0_AXIFIFO_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqDesign_FS_0_AXIFIFO_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/OpenHardware/NuclearOption/asdf/output/asdf/asdf.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_FS_0_AXIFIFO_0/ZynqDesign_FS_0_AXIFIFO_0.xci
# IP: The module: 'ZynqDesign_FS_0_AXIFIFO_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/OpenHardware/NuclearOption/asdf/output/asdf/asdf.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_FS_0_AXIFIFO_0/ZynqDesign_FS_0_AXIFIFO_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqDesign_FS_0_AXIFIFO_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/OpenHardware/NuclearOption/asdf/output/asdf/asdf.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_FS_0_AXIFIFO_0/ZynqDesign_FS_0_AXIFIFO_0/ZynqDesign_FS_0_AXIFIFO_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqDesign_FS_0_AXIFIFO_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
